
# Database Configuration using Environment Variables (Security Best Practice)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA / Hibernate properties for Prod (Safe: Never auto-delete tables)
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# user exactly url when host to production
app.cors.origins=https://your-inventory-app.railway.app